version: 2.1
jobs:  
  aws-cli-example:    
    docker:
      - image: saikrishnae/dotnet-aws:version4.0
    steps:
      - checkout
      - run:
          command: dotnet --version
      - run:
          command: aws --version
workflows:
  Socotra-Configuration-Deployment:
    jobs:
      - aws-cli-example