version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          command: |
            aws --version
            aws configure set profile $Profile
            aws configure set region $Region
            aws configure set aws_access_key_id AKIARK55DHZSJIZCT2QE
            aws configure set aws_secret_access_key w1K2b5xNdUyORlnPmo77Q53Eska/AWMlCbTbMfFU            
workflows:
  aws-cli:
    jobs:
      - aws-cli-example