version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: amazon/aws-cli:latest
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    working_directory: ~/project/AWSServerlessApplication/AWSServerlessApplication
    steps:
      - checkout
      - run:
          name: AWS CLI check
          command: aws --version           
      - run:
          name: dotnet CLI check
          command: dotnet --version
workflows:
  Deployment:
    jobs:
      - build-and-deploy