version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  dotnet-deploy:
    working_directory: ~/project/AWSServerlessApplication/AWSServerlessApplication
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Install Zip and Unzip
          command: |            
            apt-get update
            apt-get -y install zip
            apt-get -y install unzip
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Set AWS Region
          command: aws configure set region us-east-2
      - run:
          name: Set AWS Access Key
          command: aws configure set aws_access_key_id AKIARK55DHZSJIZCT2QE
      - run:
          name: Set AWS Secret Key
          command: aws configure set aws_secret_access_key w1K2b5xNdUyORlnPmo77Q53Eska/AWMlCbTbMfFU
      - run:
          name: dotnet clean
          command: |
            dotnet clean
            dotnet restore -nowarn:msb3202,nu1503 -p:RestoreUseSkipNonexistentTargets=false -v:diag
      - run:
          name: Install dotnet tools
          command: dotnet tool install --global dotnet-ef      
      - run:
          name: Install Amazon Lambda Templates
          command: dotnet new -i Amazon.Lambda.Templates::*
      - run:
          name: Install Lambda Tools
          command: |
            dotnet new tool-manifest
            dotnet tool install --global Amazon.Lambda.Tools
      - run:
          name: Set PATH for dotnet tools
          command: export PATH="$PATH:/root/.dotnet/tools"
      - run:
          name: Update
          command: dotnet tool update -g Amazon.Lambda.Tools      
      - run:
          name: Publish
          command: |
            cd AWSServerlessApplication
            ~/.dotnet/tools/dotnet-lambda deploy-serverless pwd --disable-interactive true --region us-east-2 --profile default --msbuild-parameters "--no-restore"
workflows:
  Socotra-Configuration-Deployment:
    jobs:
      - dotnet-deploy