version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest

    steps:
      - checkout     

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - run:
          name: Deploy application
          command: sls deploy --stage pre