version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          command: |
            aws --version
            echo Restore started on `date`
            export PATH="$PATH:/root/.dotnet/tools"
            aws configure set profile $Profile
            aws configure set region $Region
            aws configure set aws_access_key_id AKIARK55DHZSJIZCT2QE
            aws configure set aws_secret_access_key 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
            cd Dotnetlambda4
            cd src
            cd Dotnetlambda4
            dotnet clean 
            dotnet restore
            echo Build started on `date`
            dotnet new -i Amazon.Lambda.Templates::*
            dotnet tool install -g Amazon.Lambda.Tools
            dotnet tool update -g Amazon.Lambda.Tools
            dotnet lambda deploy-function "Dotnetlambda4" --function-role "arn:aws:iam::yourawsaccount:role/youriamroleforlambda" --region "us-east-1"
workflows:
  aws-cli:
    jobs:
      - aws-cli-example