version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          shell: cmd.exe
          command: dotnet --version
      - run:
          name: Install AWS CLI
          shell: powershell.exe
          command:
            msiexec.exe /i https://awscli.amazonaws.com/AWSCLIV2.msi