version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  dotnet-docker:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0    
    steps:
      - checkout
      - run:
          command: |
            aws-cli --version
            aws-cli configure set profile testprofile
            aws-cli configure set region us-east-2
            aws-cli configure set aws_access_key_id AKIARK55DHZSJIZCT2QE
            aws-cli configure set aws_secret_access_key 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
            pwd && ls
            echo "In aws"
            dotnet --version
            dotnet clean
            dotnet restore            
workflows:
  AWS Config Check:
    jobs:
      - dotnet-docker