version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install AWS CLI"
          shell: powershell.exe
          command:
            docker run amazon/aws-cli --version