version: '2.1'
jobs:
  dotnet-docker:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          command: |
            dotnet clean
            dotnet restore
  aws-cli-example:    
    docker:
      - image: amazon/aws-cli:latest      
    steps:
      - checkout
      - run:
          command: |
            aws --version
            aws configure set profile testprofile
            aws configure set region us-east-2
            aws configure set aws_access_key_id AKIARK55DHZSJIZCT2QE
            aws configure set aws_secret_access_key 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
            pwd && ls
            echo "In aws"
workflows:
  Socotra-Configuration-Deployment:
    jobs:
      - dotnet-docker
      - aws-cli-example:
          requires:
            - dotnet-docker
